// Default Bay Area events for 2026
const DEFAULT_EVENTS = [
    {
        id: "evt-001",
        name: "Outside Lands Music Festival",
        startDate: "2026-08-07",
        endDate: "2026-08-09",
        location: "Golden Gate Park, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-04-15",
        vendorFee: "$2,500-$5,000",
        website: "https://www.sfoutsidelands.com",
        notes: "Major food vendor opportunity. Need to apply early. Huge foot traffic.",
        tags: ["Music", "Food", "Outdoor", "Festival"]
    },
    {
        id: "evt-002",
        name: "Bay to Breakers",
        startDate: "2026-05-17",
        endDate: "2026-05-17",
        location: "Howard St to Ocean Beach, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-01",
        vendorFee: "$800-$1,500",
        website: "https://www.baytobreakers.com",
        notes: "Iconic footrace with party atmosphere. Great for beverage and snack vendors.",
        tags: ["Sports", "Outdoor", "Festival"]
    },
    {
        id: "evt-003",
        name: "SF Street Food Festival",
        startDate: "2026-08-15",
        endDate: "2026-08-15",
        location: "SoMa, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-05-01",
        vendorFee: "$500-$1,200",
        website: "https://www.sfstreetfoodfest.com",
        notes: "La Cocina's flagship event. Competitive application process.",
        tags: ["Food", "Cultural", "Outdoor"]
    },
    {
        id: "evt-004",
        name: "Eat Drink SF",
        startDate: "2026-09-11",
        endDate: "2026-09-13",
        location: "Fort Mason Center, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-06-01",
        vendorFee: "$1,000-$2,500",
        website: "https://www.eatdrinksf.com",
        notes: "Premium food and drink festival. Higher-end vendors preferred.",
        tags: ["Food", "Drink", "Indoor"]
    },
    {
        id: "evt-005",
        name: "Off the Grid: Fort Mason",
        startDate: "2026-03-27",
        endDate: "2026-10-30",
        location: "Fort Mason Center, San Francisco",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-02-15",
        vendorFee: "$150-$300/week",
        website: "https://www.offthegrid.com",
        notes: "Weekly Friday night food truck event. Season runs March–October.",
        tags: ["Food", "Weekly", "Outdoor"]
    },
    {
        id: "evt-006",
        name: "Cupertino Cherry Blossom Festival",
        startDate: "2026-04-18",
        endDate: "2026-04-19",
        location: "Memorial Park, Cupertino",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-02-28",
        vendorFee: "$300-$600",
        website: "https://www.cherryblossomfestival.org",
        notes: "Family-friendly event with craft and food vendors. Japanese cultural theme.",
        tags: ["Cultural", "Food", "Family", "Outdoor"]
    },
    {
        id: "evt-007",
        name: "San Jose Jazz Summer Fest",
        startDate: "2026-08-14",
        endDate: "2026-08-16",
        location: "Downtown San Jose",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-05-15",
        vendorFee: "$600-$1,200",
        website: "https://www.sanjosejazz.org",
        notes: "Major music festival in downtown SJ. Strong vendor program.",
        tags: ["Music", "Food", "Outdoor", "Festival"]
    },
    {
        id: "evt-008",
        name: "Oakland First Fridays",
        startDate: "2026-01-02",
        endDate: "2026-12-04",
        location: "Telegraph Ave, Oakland",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-01-01",
        vendorFee: "$75-$150/event",
        website: "https://www.oaklandfirstfridays.org",
        notes: "Monthly art walk & street fair. First Friday of every month. Rolling applications.",
        tags: ["Art", "Food", "Monthly", "Outdoor"]
    },
    {
        id: "evt-009",
        name: "SF Pride Parade & Festival",
        startDate: "2026-06-27",
        endDate: "2026-06-28",
        location: "Civic Center, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-04-01",
        vendorFee: "$800-$2,000",
        website: "https://www.sfpride.org",
        notes: "One of the largest Pride celebrations in the world. Extremely high traffic.",
        tags: ["Festival", "Cultural", "Food", "Outdoor"]
    },
    {
        id: "evt-010",
        name: "Alameda County Fair",
        startDate: "2026-06-17",
        endDate: "2026-07-05",
        location: "Alameda County Fairgrounds, Pleasanton",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-15",
        vendorFee: "$1,500-$3,500",
        website: "https://www.alamedacountyfair.com",
        notes: "Multi-week county fair. Long commitment but high revenue potential.",
        tags: ["Fair", "Food", "Family", "Outdoor"]
    },
    {
        id: "evt-011",
        name: "Treasure Island Flea Market",
        startDate: "2026-04-04",
        endDate: "2026-11-01",
        location: "Treasure Island, San Francisco",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-01",
        vendorFee: "$200-$400/day",
        website: "https://www.treasureislandflea.com",
        notes: "Monthly flea market with food vendors. First Saturday of each month, Apr–Nov.",
        tags: ["Market", "Food", "Monthly", "Outdoor"]
    },
    {
        id: "evt-012",
        name: "Ferry Building Farmers Market",
        startDate: "2026-01-03",
        endDate: "2026-12-26",
        location: "Ferry Building, San Francisco",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-01-01",
        vendorFee: "$100-$250/week",
        website: "https://www.cuesa.org/markets",
        notes: "Weekly Saturday market (Tues & Thurs too). Premium location. Competitive entry.",
        tags: ["Market", "Food", "Weekly", "Outdoor"]
    },
    {
        id: "evt-013",
        name: "KQED Live",
        startDate: "2026-10-17",
        endDate: "2026-10-17",
        location: "Craneway Pavilion, Richmond",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-07-01",
        vendorFee: "$500-$1,000",
        website: "https://www.kqed.org/live",
        notes: "Food, drink, and media event. Great exposure with KQED audience.",
        tags: ["Food", "Drink", "Media", "Indoor"]
    },
    {
        id: "evt-014",
        name: "Stern Grove Festival",
        startDate: "2026-06-14",
        endDate: "2026-08-16",
        location: "Stern Grove, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-04-01",
        vendorFee: "$300-$600/event",
        website: "https://www.sterngrove.org",
        notes: "Free Sunday concert series. Food vendors serve 5,000–10,000 per show.",
        tags: ["Music", "Food", "Outdoor", "Free"]
    },
    {
        id: "evt-015",
        name: "Gilroy Garlic Festival",
        startDate: "2026-07-24",
        endDate: "2026-07-26",
        location: "Christmas Hill Park, Gilroy",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-04-15",
        vendorFee: "$700-$1,500",
        website: "https://www.gilroygarlicfestival.org",
        notes: "Iconic garlic-themed food festival. Must incorporate garlic into menu.",
        tags: ["Food", "Festival", "Outdoor", "Family"]
    },
    {
        id: "evt-016",
        name: "Mountain View Art & Wine Festival",
        startDate: "2026-09-12",
        endDate: "2026-09-13",
        location: "Castro Street, Mountain View",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-06-15",
        vendorFee: "$500-$1,000",
        website: "https://www.miramarevents.com/mountainview",
        notes: "Premier South Bay street festival. Strong food vendor presence.",
        tags: ["Art", "Wine", "Food", "Outdoor"]
    },
    {
        id: "evt-017",
        name: "Fremont Festival of the Arts",
        startDate: "2026-08-01",
        endDate: "2026-08-02",
        location: "Downtown Fremont",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-05-15",
        vendorFee: "$400-$800",
        website: "https://www.fremontfestival.net",
        notes: "One of the largest free street festivals in the Bay Area.",
        tags: ["Art", "Food", "Outdoor", "Festival"]
    },
    {
        id: "evt-018",
        name: "Hardly Strictly Bluegrass",
        startDate: "2026-10-02",
        endDate: "2026-10-04",
        location: "Golden Gate Park, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-06-01",
        vendorFee: "$1,000-$2,500",
        website: "https://www.hardlystrictlybluegrass.com",
        notes: "Free music festival. 500K+ attendance. Limited vendor spots, very competitive.",
        tags: ["Music", "Food", "Outdoor", "Free", "Festival"]
    },
    {
        id: "evt-019",
        name: "Napa Valley Film Festival",
        startDate: "2026-11-11",
        endDate: "2026-11-15",
        location: "Downtown Napa",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-08-01",
        vendorFee: "$600-$1,200",
        website: "https://www.napavalleyfilmfest.org",
        notes: "Upscale film and food event in wine country. Affluent audience.",
        tags: ["Film", "Food", "Wine", "Indoor"]
    },
    {
        id: "evt-020",
        name: "San Francisco Chinese New Year Parade & Festival",
        startDate: "2026-02-14",
        endDate: "2026-02-21",
        location: "Chinatown, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-01-05",
        vendorFee: "$500-$1,500",
        website: "https://www.chineseparade.com",
        notes: "Largest Chinese New Year celebration outside Asia. Massive street fair.",
        tags: ["Cultural", "Food", "Festival", "Outdoor"]
    },
    {
        id: "evt-021",
        name: "Palo Alto Festival of the Arts",
        startDate: "2026-08-22",
        endDate: "2026-08-23",
        location: "University Avenue, Palo Alto",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-05-30",
        vendorFee: "$500-$900",
        website: "https://www.miramarevents.com/paloaltofestival",
        notes: "Popular Peninsula art and food festival in affluent area.",
        tags: ["Art", "Food", "Outdoor"]
    },
    {
        id: "evt-022",
        name: "Sonoma County Harvest Fair",
        startDate: "2026-10-03",
        endDate: "2026-10-04",
        location: "Sonoma County Fairgrounds, Santa Rosa",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-07-15",
        vendorFee: "$400-$800",
        website: "https://www.harvestfair.org",
        notes: "Wine, food, and agriculture celebration. Great for artisan food vendors.",
        tags: ["Food", "Wine", "Fair", "Outdoor"]
    },
    {
        id: "evt-023",
        name: "Silicon Valley Comic Con",
        startDate: "2026-08-28",
        endDate: "2026-08-30",
        location: "San Jose Convention Center",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-05-01",
        vendorFee: "$600-$1,500",
        website: "https://www.svcomiccon.com",
        notes: "Pop culture convention. Food vendor booths available inside and outside.",
        tags: ["Entertainment", "Food", "Indoor"]
    },
    {
        id: "evt-024",
        name: "Sausalito Art Festival",
        startDate: "2026-09-05",
        endDate: "2026-09-07",
        location: "Marinship Park, Sausalito",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-06-01",
        vendorFee: "$400-$900",
        website: "https://www.sausalitoartfestival.org",
        notes: "Waterfront art festival with wine garden and food vendors. Beautiful setting.",
        tags: ["Art", "Food", "Wine", "Outdoor"]
    },
    {
        id: "evt-025",
        name: "SF Cherry Blossom Festival",
        startDate: "2026-04-12",
        endDate: "2026-04-13",
        location: "Japantown, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-15",
        vendorFee: "$400-$800",
        website: "https://sfcherryblossom.org",
        notes: "58th Annual. Expanding to Sutter St this year. Nonprofit food vendors featured. Great for Japanese-inspired pastries and specialty coffee. High foot traffic.",
        tags: ["Cultural", "Food", "Festival", "Outdoor"]
    },
    {
        id: "evt-026",
        name: "Carnaval San Francisco",
        startDate: "2026-05-23",
        endDate: "2026-05-24",
        location: "Mission District, San Francisco",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-04-01",
        vendorFee: "$600-$1,500",
        website: "https://carnavalsanfrancisco.org",
        notes: "Largest multicultural celebration on the West Coast. Free 2-day festival & Grand Parade. 2026 theme: 'La Copa Del Pueblo'. Massive foot traffic in the Mission.",
        tags: ["Cultural", "Food", "Festival", "Outdoor", "Music"]
    },
    {
        id: "evt-027",
        name: "BottleRock Napa Valley",
        startDate: "2026-05-22",
        endDate: "2026-05-24",
        location: "Napa Valley Expo, Napa",
        size: "Massive",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-02-01",
        vendorFee: "$2,000-$5,000",
        website: "https://www.bottlerocknapavalley.com",
        notes: "Major 3-day music & culinary festival. 75+ bands, celebrity chef performances. Gourmet food vendor spots highly competitive. Premium audience willing to spend.",
        tags: ["Music", "Food", "Wine", "Festival", "Outdoor"]
    },
    {
        id: "evt-028",
        name: "Castro Street Fair",
        startDate: "2026-10-04",
        endDate: "2026-10-04",
        location: "Castro District, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-07-01",
        vendorFee: "$400-$900",
        website: "https://castrostreetfair.org",
        notes: "52nd Annual. SF legacy street fair celebrating LGBTQ+ community. Thousands of attendees. Food vendors support local nonprofits. Great community event.",
        tags: ["Cultural", "Food", "Festival", "Outdoor"]
    },
    {
        id: "evt-029",
        name: "EAT ME! Artisan Food Fest",
        startDate: "2026-04-04",
        endDate: "2026-04-05",
        location: "The Box SF, San Francisco",
        size: "Medium",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-20",
        vendorFee: "$300-$700",
        website: "https://www.eventbrite.com/e/eat-me-artisan-food-fest-the-box-sf-april-4-5-tickets-1983995210081",
        notes: "Artisan food festival at historic venue. Perfect for specialty bakery and coffee vendors. Intimate setting focused on food artisans.",
        tags: ["Food", "Artisan", "Indoor"]
    },
    {
        id: "evt-030",
        name: "Bay Area Brew Fest",
        startDate: "2026-04-18",
        endDate: "2026-04-18",
        location: "Presidio Main Lawn, San Francisco",
        size: "Large",
        vendorStatus: "Not Applied",
        applicationDeadline: "2026-03-15",
        vendorFee: "$500-$1,000",
        website: "https://www.eventbrite.com/e/2026-bay-area-brew-fest-tickets-1977549873907",
        notes: "Beer festival at the Presidio. Coffee vendors complement beer offerings well. Good opportunity for pastry pairings.",
        tags: ["Drink", "Food", "Festival", "Outdoor"]
    }
];
